# Use an official Python runtime as a parent image
FROM python:latest

# Set environment variables for Flask
ENV FLASK_APP=crudapp.py
ENV FLASK_ENV=development

# Ensure Gunicorn is in the PATH
ENV PATH="/usr/local/bin:$PATH"

# Set the working directory inside the container
WORKDIR /app

# Install git and other dependencies
RUN apt-get update && apt-get install -y git build-essential libpq-dev gcc

# Clone the Flask application repository
RUN git clone https://github.com/michaelthielemans/example-flask-crud.git .

# Upgrade pip and install dependencies directly (no virtual environment needed)
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Expose the port Flask will run on
EXPOSE 8000

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

# Set the entrypoint to run the script
ENTRYPOINT ["/app/entrypoint.sh"]
