# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV FLASK_APP=crudapp.py
ENV FLASK_ENV=development

# Set the working directory inside the container
WORKDIR /app
    
RUN git clone https://github.com/gurkanakdeniz/example-flask-crud.git

# Activate virtual environment and install dependencies
RUN . /app/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Expose the port Flask runs on
EXPOSE 5000

# Initialize, migrate, and upgrade the database
RUN . /app/venv/bin/activate && \
    flask db init && \
    flask db migrate -m "entries table" && \
    flask db upgrade

# Start the Flask application
CMD ["/bin/bash", "-c", ". /app/venv/bin/activate && flask run --host=0.0.0.0"]
